name: Generate SBOM Report and Validate Security

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  validate-and-scan:
    name: Validate Kubernetes YAMLs and Scan for Vulnerabilities
    runs-on: ubuntu-latest
    
    steps:
    # Step 1: Checkout Repository
    - name: Checkout Repository
      uses: actions/checkout@v3

    # Step 2: Generate SBOM with Anchore SBOM Action
    - name: Generate SBOM
      uses: anchore/sbom-action@v0
      with:
        image: docker.io/nginx:1.14.2

    # Optionally publish SBOM to GitHub releases (if desired)
    - name: Publish SBOM to Release
      uses: anchore/sbom-action/publish-sbom@v0
      with:
        sbom-artifact-match: ".*\\.spdx$"

    # Step 3: Lint Kubernetes Manifests Using KubeLinter
    - name: Scan YAMLs
      id: kube-lint-scan
      uses: stackrox/kube-linter-action@v1
      with:
        directory: manifest

    # Step 4: Run Trivy Vulnerability Scanner
    - name: Run Trivy Vulnerability Scanner
      uses: aquasecurity/trivy-action@0.58.0
      with:
        image-ref: 'docker.io/nginx:1.14.2:${{ github.sha }}'
        format: 'table'                      # Output format in a table for readability
        exit-code: '1'                       # Fail the workflow on detecting vulnerabilities
        ignore-unfixed: true                 # Ignore vulnerabilities without available fixes
        vuln-type: 'os,library'              # Scan OS packages and libraries
        severity: 'CRITICAL,HIGH'            # Focus on high and critical severity issues
